"""Deterministic telemetry-derived synthetic diagnostics."""

from tuneros.diagnostics.catalog import (
    BATTERY,
    COOLANT,
    ENGINE_RUNNING,
    FRONT_LEFT_WHEEL_SPEED,
    FRONT_RIGHT_WHEEL_SPEED,
    MANIFOLD_PRESSURE,
    OIL,
    REAR_LEFT_WHEEL_SPEED,
    REAR_RIGHT_WHEEL_SPEED,
    VEHICLE_SPEED,
    DiagnosticCatalog,
    DiagnosticRule,
    create_default_diagnostic_catalog,
)
from tuneros.diagnostics.engine import DEFAULT_DIAGNOSTIC_EVENT_CAPACITY, DiagnosticEngine
from tuneros.diagnostics.models import (
    DiagnosticClearError,
    DiagnosticDefinition,
    DiagnosticError,
    DiagnosticEvent,
    DiagnosticEventType,
    DiagnosticFreezeFrame,
    DiagnosticSeverity,
    DiagnosticSnapshot,
    DiagnosticStatus,
    DiagnosticTroubleCode,
    FreezeFrameSignal,
    UnknownDiagnosticCodeError,
)

__all__ = [
    "BATTERY",
    "COOLANT",
    "DEFAULT_DIAGNOSTIC_EVENT_CAPACITY",
    "ENGINE_RUNNING",
    "FRONT_LEFT_WHEEL_SPEED",
    "FRONT_RIGHT_WHEEL_SPEED",
    "MANIFOLD_PRESSURE",
    "OIL",
    "REAR_LEFT_WHEEL_SPEED",
    "REAR_RIGHT_WHEEL_SPEED",
    "VEHICLE_SPEED",
    "DiagnosticCatalog",
    "DiagnosticClearError",
    "DiagnosticDefinition",
    "DiagnosticEngine",
    "DiagnosticError",
    "DiagnosticEvent",
    "DiagnosticEventType",
    "DiagnosticFreezeFrame",
    "DiagnosticRule",
    "DiagnosticSeverity",
    "DiagnosticSnapshot",
    "DiagnosticStatus",
    "DiagnosticTroubleCode",
    "FreezeFrameSignal",
    "UnknownDiagnosticCodeError",
    "create_default_diagnostic_catalog",
]
